import type { Game } from '@/types/game';

export const GAMES: Game[] = [
    // Featured Games (Hot & New)
    {
        id: 'subway-surfers',
        title: 'Subway Surfers',
        description: 'Dash as fast as you can through the subway and dodge the oncoming trains!',
        thumbnail: 'https://img.gamedistribution.com/8baa45aabd504c1ab7a6c4ee9b1a336f-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/8baa45aabd504c1ab7a6c4ee9b1a336f/',
        category: 'Arcade',
        tags: ['Arcade', 'Running'],
        isFeatured: true,
        isHot: true,
    },
    {
        id: 'bubble-shooter',
        title: 'Bubble Shooter Witch Tower 2',
        description: 'Boom! Hear that pop? The bubbles are calling! This classic bubble shooter blends quick reflexes with clever strategy. Spin the Lucky Wheel for extra rewards, claim weekly bonus and dive into a bright, cute world that never runs out of fun.',
        thumbnail: 'https://img.gamedistribution.com/8b43e10dbeb84f7c90e848fb8109d489-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/8b43e10dbeb84f7c90e848fb8109d489/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Bubble'],
        isFeatured: true,
        isNew: true,
    },
    {
        id: 'penalty-shooters-2',
        title: 'Penalty Shooters 2',
        description: 'Sequel to the classic football penalty shootout game brings more leagues and improved competition system.',
        thumbnail: 'https://img.gamedistribution.com/571b9df027e449f78e3869ba19658754-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/571b9df027e449f78e3869ba19658754/',
        category: 'Sports',
        tags: ['Sports', 'Soccer'],
        isFeatured: true,
        isHot: true,
    },
    {
        id: 'moto-x3m',
        title: 'Moto X3M',
        description: 'Racing game enthusiasts, are you ready? This is a game that is going to make your adrenaline skyrocket - Moto X3M Dead Ahead! It\'s an exciting blend of motor, driving, and even a bit of shooting. Driving a cool motorcycle, take your partner with you and race through tricky tracks.',
        thumbnail: 'https://img.gamedistribution.com/8593f8d7add14ad398d9cece72ee7283-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/8593f8d7add14ad398d9cece72ee7283/',
        category: 'Racing',
        tags: ['Racing', 'Motorcycle'],
        isFeatured: true,
        isNew: true,
    },

    // Action Games
    {
        id: 'stickman-hook',
        title: 'Stickman Hook',
        description: 'Tap to hook and make incredible jumps; avoid every obstacle in your way!',
        thumbnail: 'https://img.gamedistribution.com/599e07f9ed074845aa099aed24b9006c-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/599e07f9ed074845aa099aed24b9006c/',
        category: 'Action',
        tags: ['Action', 'Arcade'],
    },
    {
        id: 'zombie-mission',
        title: 'Zombie Mission',
        description: 'The Zombie Mission 10 Prison Breakout episode is not over yet! A new call came to the heroes from the secret part of the prison',
        thumbnail: 'https://img.gamedistribution.com/c7b2613236134ae99e4cc253183f8ff0-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/c7b2613236134ae99e4cc253183f8ff0/',
        category: 'Action',
        tags: ['Action', 'Shooter'],
    },
    {
        id: 'ninja-hands',
        title: 'Ninja Hands',
        description: 'Test your reflexes and slice fruits like a true ninja warrior!',
        thumbnail: 'https://img.gamedistribution.com/c183eb3362b54a719851c703bb630e48-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/c8fe12a5e8a742c7b37b67d5b47c8794/',
        category: 'Action',
        tags: ['Action', 'Casual'],
    },

    // Puzzle Games
    {
        id: 'candy-bubble',
        title: 'Candy Bubble',
        description: 'Match colorful candy bubbles in this sweet puzzle adventure!',
        thumbnail: 'https://img.gamedistribution.com/d4a4258e68d54e2ba75fc3b29805571d-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/d4a4258e68d54e2ba75fc3b29805571d/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Match-3'],
    },
    {
        id: 'block-puzzle-jewel',
        title: 'Block Puzzle Jewel',
        description: 'Drag and drop blocks to create and destroy full lines!',
        thumbnail: 'https://img.gamedistribution.com/a66111e097d24ffeb92f45161f21db29-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/a66111e097d24ffeb92f45161f21db29/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Logic'],
    },
    {
        id: 'mahjong-connect-classic',
        title: 'Mahjong Connect Classic',
        description: 'Enter the enchanting world of Magic & Wizards Mahjong! Match mystical tiles adorned with runes, potions, and magical artifacts across beautifully crafted layouts. Enjoy smooth gameplay with boosters like Hint, Shuffle, Undo, Torch, and Freeze.',
        thumbnail: 'https://img.gamedistribution.com/769f3b2834b94b7ea57a8aa899d93272-1280x550.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/769f3b2834b94b7ea57a8aa899d93272/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Mahjong'],
    },
    {
        id: 'sudoku-classic',
        title: 'Sudoku Classic',
        description: 'Sudoku Classic" is a timeless puzzle game played on a 9x9 grid. The objective is to fill every row, column, and 3x3 square with the numbers 1-9, ensuring that no number is repeated within the same row, column, or square. LofGames has designed an easy-to-use interface and added various features to enhance your experience while enjoying this classic Sudoku game.',
        thumbnail: 'https://img.gamedistribution.com/cbb50b90ed904252849de31f7647a0e7-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/cbb50b90ed904252849de31f7647a0e7/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Logic'],
    },

    // Arcade Games
    {
        id: 'pac-man',
        title: 'Pac-Man',
        description: 'You wake up alone in an empty apartment where everything seems calm… until the first knock at the door. Nameless parcels, mysterious objects, eerie creatures, and meaningless incantations turn your cozy home into a nightmarish trap. Who is sending you these items — an enemy or a savior? Why do toys come to life, eyes grow on the walls, and a ceiling-high worm bursts from the bathtub',
        thumbnail: 'https://img.gamedistribution.com/f618546bbe6a42b4850156aebb8c202e-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/f618546bbe6a42b4850156aebb8c202e/',
        category: 'Arcade',
        tags: ['Arcade', 'Classic'],
    },
    {
        id: 'flappy-bird-original',
        title: 'Flappy Bird',
        description: 'An addicted hypercasual game, simple to control, nice design, fun and relax-able.',
        thumbnail: 'https://img.gamedistribution.com/c6630e744bae4404b903ec3966db721b-512x512.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/c6630e744bae4404b903ec3966db721b/',
        category: 'Arcade',
        tags: ['Arcade', 'Casual'],
    },
    {
        id: 'snake-io',
        title: 'Snake.io',
        description: 'Snake Classic: A modern twist on the nostalgic snake game. Navigate your snake through six unique modes: Classic, Box, Tunnel, Mill, Condo, and Rail. Collect fruits and gems, customize your snake with skins, and enjoy multi-language support. Compete on personal leaderboards and play on both PC and mobile. Fun and engaging for all ages!',
        thumbnail: 'https://img.gamedistribution.com/2609b48eea7d40ebb414a1211dfed2af-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/2609b48eea7d40ebb414a1211dfed2af/',
        category: 'Arcade',
        tags: ['Arcade', 'Multiplayer'],
    },
    {
        id: 'brick-breaker-deluxe',
        title: 'Brick Breaker Deluxe',
        description: 'Break bricks, collect power-ups for more fun breaking bricks and watch Chipy Chipy Chipa Cat and El Primo Bara Bere dancing. Go through interesting and exciting levels in the fun game about Chippy Chippy Chippy Chappa Chappa Cat and El Primo. Pass levels of different difficulty and set a personal record.',
        thumbnail: 'https://img.gamedistribution.com/6fe210242c6e45a68a4d78293eb91086-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/6fe210242c6e45a68a4d78293eb91086/',
        category: 'Arcade',
        tags: ['Arcade', 'Classic'],
    },

    // Sports Games
    {
        id: 'basketball-stars',
        title: 'Basketball Stars',
        description: 'Ready for the most exciting basketball gameJoin the excitement with different mapsShow your game to everyone by making your best shot',
        thumbnail: 'https://img.gamedistribution.com/2d99b4bd747b4e8b80375f8f5c526665-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/2d99b4bd747b4e8b80375f8f5c526665/',
        category: 'Sports',
        tags: ['Sports', 'Basketball'],
    },
    {
        id: 'golf-battle',
        title: 'Golf Battle',
        description: 'Mini Golf Battle is a casual sports puzzle where precision and timing decide the outcome. Your task is to sink the ball into the hole with the fewest strokes possible while navigating ramps, walls, and tricky obstacles. Special power-ups like Fire, Wing, and Spring shots add variety, letting you approach each course with unique strategies. Whether for short play sessions or longer runs, Mini Golf Battle delivers an engaging mix of relaxation and skillful play.',
        thumbnail: 'https://img.gamedistribution.com/f13a0ab3316c4be8b273610a5f2c872c-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/f13a0ab3316c4be8b273610a5f2c872c/',
        category: 'Sports',
        tags: ['Sports', 'Golf'],
    },
    {
        id: 'soccer-skills',
        title: 'Soccer Skills',
        description: 'Run as far as you can without being tackled swerve jump and duck past opponents Collect powerups and upgrade your player',
        thumbnail: 'https://img.gamedistribution.com/54df6d78ccde4de1b41acadb002f1722.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/54df6d78ccde4de1b41acadb002f1722/',
        category: 'Sports',
        tags: ['Sports', 'Soccer'],
    },

    // Strategy Games
    {
        id: 'tower-defense-kingdom',
        title: 'Tower Defense Kingdom',
        description: 'Build towers and defend your kingdom from waves of enemies!',
        thumbnail: 'https://img.gamedistribution.com/ab7bfc59b5384e3cb8b52cce910c43da-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/ab7bfc59b5384e3cb8b52cce910c43da/',
        category: 'Strategy',
        tags: ['Strategy', 'Defense'],
    },
    {
        id: 'chess-online',
        title: 'Chess Online',
        description: 'Play chess against AI or friends. Master the ultimate strategy game!',
        thumbnail: 'https://img.gamedistribution.com/b80ebde6ee1b4adfaa96398a4261db80-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/b80ebde6ee1b4adfaa96398a4261db80/',
        category: 'Strategy',
        tags: ['Strategy', 'Board'],
    },
    {
        id: 'empire-war',
        title: 'Empire War',
        description: 'Build and manage your empire. Expand your territory and conquer!',
        thumbnail: 'https://img.gamedistribution.com/ca12cc5666a1430aa557452c3fbb0039-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/ca12cc5666a1430aa557452c3fbb0039/',
        category: 'Strategy',
        tags: ['Strategy', 'War'],
    },

    // Adventure Games
    {
        id: 'fireboy-watergirl',
        title: 'Fireboy and Watergirl',
        description: 'Fireboy and Watergirl made by Oslo Albet are exploring the Forest Temple in search of diamonds Switch between Fireboy Watergirl and play alone or together as players The goal is to reach the exit safely so be careful Fireboy cannot touch water and Watergirl cannot touch fire.',
        thumbnail: 'https://img.gamedistribution.com/1c60c96ecd6f4d928497c7eaa58f150f-512x512.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/1c60c96ecd6f4d928497c7eaa58f150f/',
        category: 'Adventure',
        tags: ['Adventure', 'Puzzle'],
    },
    {
        id: 'temple-run',
        title: 'Temple Run',
        description: 'Embark on a temple adventure in Bubble Shooter Temple Jewels! Pop colorful bubbles as you progress through ancient ruins inspired by Central American temples. Keep track of your journey with the Stats screen, showing your best, current, and previous scores across Novice, Expert, and Master modes. With vibrant visuals, exciting challenges, and detailed progress tracking, this bubble shooter keeps you motivated to aim higher and improve every round!',
        thumbnail: 'https://img.gamedistribution.com/8b43e10dbeb84f7c90e848fb8109d489-512x512.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/8b43e10dbeb84f7c90e848fb8109d489/',
        category: 'Adventure',
        tags: ['Adventure', 'Running'],
    },
    {
        id: 'jungle-adventure',
        title: 'Jungle Adventure',
        description: 'Our hero has ventured into a journey through a jungle full of dangers help him avoiding threats and catching jewels by the way',
        thumbnail: 'https://img.gamedistribution.com/b09217e7cd1944d1b50c547f86c34ca3-1280x720.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/b09217e7cd1944d1b50c547f86c34ca3/',
        category: 'Adventure',
        tags: ['Adventure', 'Exploration'],
    },

    // Racing Games
    {
        id: 'snake-hunter',
        title: 'Snake Hunter',
        description: '"Snake Hunter" – Giant serpents are invading our homeland! Grab your weapons, fortify our defenses, and slay the monstrous snakes to protect our land. In this game, you play as a guardian, battling each segment of the serpent\'s massive body.Collect skills and upgrade buffs dropped by the snakes to enhance your weapon\'s power and abilities. As you face different serpents across various levels, you\'ll need to strategically choose skills to counter their attacks and emerge victorious.',
        thumbnail: 'https://img.gamedistribution.com/c3e55a6771b942b893f0e472d31ae4ab-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/c3e55a6771b942b893f0e472d31ae4ab/',
        category: 'Racing',
        tags: ['Racing', 'Drifting'],
    },
    {
        id: 'hill-climb-racing',
        title: 'Hill Climb Racing',
        description: 'Control your car or bike to climb hills with most realistic control to face the challenges of unique uphill & downhill environments. Gain bonuses from tricks and collect coins to upgrade your car and reach even higher distances. Use Arrow keys or WASD to control the car.',
        thumbnail: 'https://img.gamedistribution.com/ddcba9beafaf409ab581385023761cde-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/ddcba9beafaf409ab581385023761cde/',
        category: 'Racing',
        tags: ['Racing', 'Casual'],
    },

    // Simulation Games
    {
        id: 'city-builder',
        title: 'City Builder',
        description: 'How do you become the mayor of your town? Find the right valley and build everything from scratch with your own hands. Then the residents will help you make your town even better and even share their equipment',
        thumbnail: 'https://img.gamedistribution.com/16e9c7553adc435a96bf6bb5274fe3c5-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/16e9c7553adc435a96bf6bb5274fe3c5/',
        category: 'Simulation',
        tags: ['Simulation', 'Management'],
    },
    {
        id: 'farm-simulator',
        title: 'Farm Simulator',
        description: 'Become a modern farmer in Indian Tractor Farm Simulator! Immerse yourself in a huge open world and harvest many types of crops, take care of your livestock - cows, sheep, and pigs - take part in forestry, and sell your products on a dynamic market to expand your farm!',
        thumbnail: 'https://img.gamedistribution.com/94877d38c7384ca2b24ab14173d2432a-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/94877d38c7384ca2b24ab14173d2432a/',
        category: 'Simulation',
        tags: ['Simulation', 'Farming'],
    },

    // RPG Games
    {
        id: 'dungeon-crawl',
        title: 'Dungeon Crawl',
        description: 'Minimal Dungeon RPG is an innovative RPG that is based on the classic one. Multiple rooms are connected into dungeons. Tasks, monsters, and rewards are all simplified into squares in the rooms. You can just click on the squares to play and crawl through the dungeons. A fan of dungeon crawlers will not want to miss the game! A rich and immersive storyline runs throughout the whole game. It’s quite simple, easy and fun!',
        thumbnail: 'https://img.gamedistribution.com/215b2093921141c9b8634a42f48ddbdb-512x384.jpeg',
        iframeUrl: 'https://html5.gamedistribution.com/215b2093921141c9b8634a42f48ddbdb/',
        category: 'RPG',
        tags: ['RPG', 'Fantasy'],
    },
    {
        id: 'merge-pixel',
        title: 'Merge Pixel',
        description: 'Attractive characters in dot, pixel style! Combining the same characters creates a higher level of characters. Repeat Merge to create a legendary character.',
        thumbnail: 'https://img.gamedistribution.com/72b219a0450c465c81f3cd1ebdafb815-512x384.jpg',
        iframeUrl: 'https://html5.gamedistribution.com/72b219a0450c465c81f3cd1ebdafb815/',
        category: 'RPG',
        tags: ['RPG', 'Retro'],
    },
];

export const CATEGORIES: Game['category'][] = [
    'Action',
    'Puzzle',
    'Arcade',
    'Sports',
    'Strategy',
    'Adventure',
    'Racing',
    'Simulation',
    'RPG',
];