import type { Game } from '@/types/game';

export const GAMES: Game[] = [
    // Featured Games (Hot & New)
    {
        id: 'stickman-hook',
        title: 'Stickman Hook',
        description: 'Tap to hook and make incredible jumps; Avoid every obstacle that stands in your way.',
        thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/c0d6a1e3f8f84e2c8e8e8e8e8e8e8e8e/',
        category: 'Action',
        tags: ['Action', 'Arcade'],
        isFeatured: true,
        isHot: true,
    },
    {
        id: 'bubble-shooter',
        title: 'Bubble Shooter',
        description: 'Classic bubble shooter game. Match 3 or more bubbles of the same color to pop them.',
        thumbnail: 'https://images.unsplash.com/photo-1614294148960-9aa740632a87?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/d4cf5e8c8e8e8e8e8e8e8e8e8e8e8e8e/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Casual'],
        isFeatured: true,
        isNew: true,
    },
    {
        id: 'subway-surfers',
        title: 'Subway Surfers',
        description: 'Dash as fast as you can through the subway and dodge the oncoming trains!',
        thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6/',
        category: 'Arcade',
        tags: ['Arcade', 'Running'],
        isFeatured: true,
        isHot: true,
    },
    {
        id: 'racing-thunder',
        title: 'Racing Thunder',
        description: 'Experience high-speed racing action with stunning graphics and intense competition.',
        thumbnail: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7/',
        category: 'Racing',
        tags: ['Racing', 'Sports'],
        isFeatured: true,
        isNew: true,
    },

    // Action Games
    {
        id: 'zombie-shooter',
        title: 'Zombie Shooter',
        description: 'Survive the zombie apocalypse! Shoot all zombies and save humanity.',
        thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8/',
        category: 'Action',
        tags: ['Action', 'Shooter'],
    },
    {
        id: 'ninja-run',
        title: 'Ninja Run',
        description: 'Run, jump and slide through challenging obstacles as a skilled ninja warrior.',
        thumbnail: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9/',
        category: 'Action',
        tags: ['Action', 'Adventure'],
    },
    {
        id: 'space-shooter',
        title: 'Space Shooter',
        description: 'Defend the galaxy from alien invaders in this classic space shooter.',
        thumbnail: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0/',
        category: 'Action',
        tags: ['Action', 'Shooter'],
    },

    // Puzzle Games
    {
        id: 'candy-match',
        title: 'Candy Match',
        description: 'Match colorful candies in this sweet puzzle adventure. Complete levels and earn stars!',
        thumbnail: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Match-3'],
    },
    {
        id: 'block-puzzle',
        title: 'Block Puzzle',
        description: 'Drag and drop blocks to create and destroy full lines. A classic puzzle game!',
        thumbnail: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Logic'],
    },
    {
        id: 'mahjong-connect',
        title: 'Mahjong Connect',
        description: 'Connect matching tiles to clear the board in this relaxing puzzle game.',
        thumbnail: 'https://images.unsplash.com/photo-1566694271453-390536dd1f0d?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Mahjong'],
    },
    {
        id: 'sudoku-master',
        title: 'Sudoku Master',
        description: 'Challenge your brain with classic Sudoku puzzles of varying difficulty.',
        thumbnail: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4/',
        category: 'Puzzle',
        tags: ['Puzzle', 'Logic'],
    },

    // Arcade Games
    {
        id: 'pac-runner',
        title: 'Pac Runner',
        description: 'Run through the maze, collect dots, and avoid ghosts in this classic arcade game.',
        thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5/',
        category: 'Arcade',
        tags: ['Arcade', 'Classic'],
    },
    {
        id: 'flappy-bird',
        title: 'Flappy Bird',
        description: 'Tap to flap and navigate through pipes. How far can you go?',
        thumbnail: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6/',
        category: 'Arcade',
        tags: ['Arcade', 'Casual'],
    },
    {
        id: 'snake-classic',
        title: 'Snake Classic',
        description: 'The timeless snake game. Eat food, grow longer, and avoid hitting yourself!',
        thumbnail: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7/',
        category: 'Arcade',
        tags: ['Arcade', 'Classic'],
    },
    {
        id: 'brick-breaker',
        title: 'Brick Breaker',
        description: 'Break all the bricks with your ball and paddle. Classic arcade fun!',
        thumbnail: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8/',
        category: 'Arcade',
        tags: ['Arcade', 'Classic'],
    },

    // Sports Games
    {
        id: 'soccer-stars',
        title: 'Soccer Stars',
        description: 'Flick and score! Compete in fast-paced soccer matches against opponents.',
        thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9/',
        category: 'Sports',
        tags: ['Sports', 'Soccer'],
    },
    {
        id: 'basketball-legends',
        title: 'Basketball Legends',
        description: 'Shoot hoops and become a basketball legend in this exciting sports game.',
        thumbnail: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0/',
        category: 'Sports',
        tags: ['Sports', 'Basketball'],
    },
    {
        id: 'golf-master',
        title: 'Golf Master',
        description: 'Perfect your swing and master challenging golf courses around the world.',
        thumbnail: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1/',
        category: 'Sports',
        tags: ['Sports', 'Golf'],
    },

    // Strategy Games
    {
        id: 'tower-defense',
        title: 'Tower Defense',
        description: 'Build towers and defend your base from waves of enemies. Strategic gameplay!',
        thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2/',
        category: 'Strategy',
        tags: ['Strategy', 'Defense'],
    },
    {
        id: 'chess-master',
        title: 'Chess Master',
        description: 'Play chess against AI or friends. Master the ultimate strategy game.',
        thumbnail: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3/',
        category: 'Strategy',
        tags: ['Strategy', 'Board'],
    },
    {
        id: 'empire-builder',
        title: 'Empire Builder',
        description: 'Build and manage your empire. Expand your territory and conquer the world!',
        thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4/',
        category: 'Strategy',
        tags: ['Strategy', 'Simulation'],
    },

    // Adventure Games
    {
        id: 'treasure-hunt',
        title: 'Treasure Hunt',
        description: 'Explore mysterious islands and discover hidden treasures in this adventure game.',
        thumbnail: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5/',
        category: 'Adventure',
        tags: ['Adventure', 'Exploration'],
    },
    {
        id: 'dungeon-quest',
        title: 'Dungeon Quest',
        description: 'Venture into dark dungeons, fight monsters, and collect legendary loot.',
        thumbnail: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6/',
        category: 'Adventure',
        tags: ['Adventure', 'RPG'],
    },
    {
        id: 'jungle-explorer',
        title: 'Jungle Explorer',
        description: 'Navigate through dense jungles, avoid dangers, and discover ancient ruins.',
        thumbnail: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7/',
        category: 'Adventure',
        tags: ['Adventure', 'Exploration'],
    },

    // Racing Games
    {
        id: 'drift-kings',
        title: 'Drift Kings',
        description: 'Master the art of drifting in high-speed racing competitions.',
        thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8/',
        category: 'Racing',
        tags: ['Racing', 'Drifting'],
    },
    {
        id: 'moto-x3m',
        title: 'Moto X3M',
        description: 'Race your motorbike through challenging obstacle courses and perform stunts.',
        thumbnail: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9/',
        category: 'Racing',
        tags: ['Racing', 'Motorcycle'],
    },

    // Simulation Games
    {
        id: 'city-builder',
        title: 'City Builder',
        description: 'Build and manage your dream city. Balance resources and keep citizens happy.',
        thumbnail: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0/',
        category: 'Simulation',
        tags: ['Simulation', 'Management'],
    },
    {
        id: 'farm-frenzy',
        title: 'Farm Frenzy',
        description: 'Manage your farm, raise animals, and grow crops in this fun simulation.',
        thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1/',
        category: 'Simulation',
        tags: ['Simulation', 'Farming'],
    },

    // RPG Games
    {
        id: 'fantasy-quest',
        title: 'Fantasy Quest',
        description: 'Embark on an epic fantasy adventure. Level up, collect items, and defeat bosses.',
        thumbnail: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2/',
        category: 'RPG',
        tags: ['RPG', 'Fantasy'],
    },
    {
        id: 'pixel-warriors',
        title: 'Pixel Warriors',
        description: 'Retro-style RPG with pixel art graphics. Battle enemies and save the kingdom.',
        thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=512&h=512&fit=crop',
        iframeUrl: 'https://html5.gamedistribution.com/b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3/',
        category: 'RPG',
        tags: ['RPG', 'Retro'],
    },
];

export const CATEGORIES: Game['category'][] = [
    'Action',
    'Puzzle',
    'Arcade',
    'Sports',
    'Strategy',
    'Adventure',
    'Racing',
    'Simulation',
    'RPG',
];